### ISSUE TITLE
Command line arguments parser and environment configurator

### ISSUE THREAD

**Issue by thadumi** [thadumi/osproject#1]
Crea a parser that analyses the command line arguments passed to the shell when it is started. The parser should check for parameters as --outputfile, --inputfile, --templatefile, and other that could be used to create a template file (the template file will be used to define how to write the log file). It also has to support shos from the arguments -ie -if and of that are --inputfile and --outputfile respectively. 
After that, the parser should pass the information grabbed from the CLI to a system that will care about the management of all the settings. The information could be passed using a struct in the form { '<argument>' : '<value>' }.
It will be nice to have a trrt forms from the arguments -ie -if and of that are --inputfile and --outputfile respectively. 
After that, the parser should pass the information grabbed from the CLI to a system that will care about the management of all the settings. The information could be passed using a struct in the form { '<argument>' : '<value>' }.
It will be nice to have a true environment configurator that, using the CLI, interact with the user to understand how to create the log's template file (and other stuff, ie arguments values).

**Comment by Extrance** [comment]
QUESTIONS ABOUT ISSUE #1
 
"Create a parser that analyses the command line arguments passed to the shell when it is started."
---This part is ok.
 
 
"The parser should check for parameters as --outputfile, --inputfile, --templatefile, and other that could be used to create a template file (the template file will be used to define how to write the log file). It also has to support shos from the arguments -ie -if and of that are --inputfile and --outputfile respectively."
---This part is ok.
 
"After that, the parser should pass the information grabbed from the CLI to a system that will care about the management of all the settings. The information could be passed using a struct in the form { '' : '' }."
---So do I have to create the Parser or also the "system that will care about the management of all the settings"?
---Anyway, in this version of the Parser I assumed that the arguments such as outputfile, and so on are already declared as global variables, so in the parser when I receive the names for the files I just open them or I just change the values of other global parameters such as maxlen and code, but if needed I may just pass those arguments to other functions or that "system", instead of directly open the files.
 
"It will be nice to have a trrt forms from the arguments -ie -if and of that are --inputfile and --outputfile respectively."
---This part is ok.
 
"It will be nice to have a true environment configurator that, using the CLI, interact with the user to understand how to create the log's template file (and other stuff, ie arguments values)."
---I didn't understand this part. When shall it be used? Only if the user choose a different template file, or what?
---This environment has to be implemented, first please tell me if the way the parser works is ok or not, and if so, what I need to change.
.
.
.
.
SORRY FOR THE LONG POST, HERE'S A POTATO
https://www.amazon.com/produce-aisle-Russet-Potato-Large/dp/B000NSKB7Q

**Comment by thadumi** [comment]
> Anyway, in this version of the Parser I assumed that the arguments such as outputfile, and so on are already declared as global variables, so in the parser when I receive the names for the files I just open them or I just change the values of other global parameters such as maxlen and code, but if needed I may just pass those arguments to other functions or that "system", instead of directly open the files

Yes, there will be global variables but before you set them, you have to check and validate parameters, ie check if the template file exists. If something is wrong you should send an error and set a default value to the parameter or you could run the environment what will interact with the user to reset some or all the parameters again.

ie. 
I run shell -if='asd.dsa' and that file doesn't exist. In this case, the parser, when it evaluates the parameter, could say "error trying to open the file $if, file not found" and then abort the shell or could say "can't find the file $if, do you want to set it now (1) or live the default one (2)? " and the user will type 1 or 2. The shell could have a parameter like --dialog-set-mode=on with which on the starting up it will make questions like that for every possible parameter.
